CREATE TABLE PARTS
(
  PART_ID       CHAR(4) NOT NULL,
  PART_NAME     VARCHAR2(255),
  PART_COLOR    VARCHAR2(30),
  PART_WEIGHT   VARCHAR2(255)
);

CREATE TABLE SHIP_VIA
(
  SHIPPER_ID     NUMBER(2) NOT NULL,
  SHIPPER_NAME   VARCHAR2(30)
);

CREATE TABLE STATUS
(
  STATUS_ID     NUMBER(2) NOT NULL,
  STATUS_NAME   VARCHAR2(30)
);

CREATE TABLE SUPPLIER
(
  SUPPLIER_ID       VARCHAR2(10) NOT NULL,
  SUPPLIER_NAME     VARCHAR2(30),
  SUPPLIER_STATUS   NUMBER(2),
  SUPPLIER_CITY     VARCHAR2(30),
  SUPPLIER_STATE    VARCHAR2(2)
);

CREATE TABLE SUPPLIER_PARTS
(
  SUPPLIER_ID   VARCHAR2(10) NOT NULL,
  PART_ID       CHAR(4) NOT NULL,
  QUANTITY      NUMBER(3),
  SHIPPER_ID    NUMBER(2)
);

ALTER TABLE PARTS
  ADD CONSTRAINT PK_PARTS
    PRIMARY KEY (PART_ID);

ALTER TABLE SHIP_VIA
  ADD CONSTRAINT PK_SHIP_VIA
    PRIMARY KEY (SHIPPER_ID);

ALTER TABLE STATUS
  ADD CONSTRAINT PK_STATUS
    PRIMARY KEY (STATUS_ID);

ALTER TABLE SUPPLIER
  ADD CONSTRAINT PK_SUPPLIER
    PRIMARY KEY (SUPPLIER_ID);

ALTER TABLE SUPPLIER_PARTS
  ADD CONSTRAINT PK_SUPPLIER_PARTS
    PRIMARY KEY (SUPPLIER_ID,PART_ID);

ALTER TABLE SUPPLIER
  ADD CONSTRAINT FK_SPLIER_STATS
    FOREIGN KEY (SUPPLIER_STATUS)
    REFERENCES STATUS(STATUS_ID);

ALTER TABLE SUPPLIER_PARTS
  ADD CONSTRAINT FK_SPLIER_PRTS_SPLY
    FOREIGN KEY (SUPPLIER_ID)
    REFERENCES SUPPLIER(SUPPLIER_ID);

ALTER TABLE SUPPLIER_PARTS
  ADD CONSTRAINT FK_SPLIER_PRTS_PRTS
    FOREIGN KEY (PART_ID)
    REFERENCES PARTS(PART_ID);

commit;
