CREATE TABLE PARTS
(
  PART_ID       VARCHAR(50) NOT NULL,
  PART_NAME     VARCHAR(255),
  PART_COLOR    VARCHAR(30),
  PART_WEIGHT   VARCHAR(255)
)
GO

CREATE TABLE SHIP_VIA
(
  SHIPPER_ID     DECIMAL(2) NOT NULL,
  SHIPPER_NAME   VARCHAR(30)
)
GO

CREATE TABLE STATUS
(
  STATUS_ID     DECIMAL(2) NOT NULL,
  STATUS_NAME   VARCHAR(30)
)
GO

CREATE TABLE SUPPLIER
(
  SUPPLIER_ID       VARCHAR(10) NOT NULL,
  SUPPLIER_NAME     VARCHAR(30),
  SUPPLIER_STATUS   DECIMAL(2),
  SUPPLIER_CITY     VARCHAR(30),
  SUPPLIER_STATE    VARCHAR(2)
)
GO

CREATE TABLE SUPPLIER_PARTS
(
  SUPPLIER_ID   VARCHAR(10) NOT NULL,
  PART_ID       VARCHAR(50) NOT NULL,
  QUANTITY      DECIMAL(3),
  SHIPPER_ID    DECIMAL(2)
)
GO
